import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ToastProvider } from "@/contexts/ToastContext";
import ToastContainer from "@/components/main-components/tissue/ToastContainer/ToastContainer";
import { UserProvider } from "./providers/UserProvider";

import { ShowCommentsProvider } from "./providers/ShowCommentsProvider";
import { ModalProvider } from "@/contexts/ModalContext";
import SignInPopUp from "@/components/landing-page/organ/popups/signin-popup/SignInPopUp";
import SignUpPopUp from "@/components/landing-page/organ/popups/signup-popup/SignUpPopUp";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ModalProvider>
          <UserProvider>
            <ToastProvider>
              <ShowCommentsProvider>
                {children}
                <SignInPopUp />
                <SignUpPopUp />
              </ShowCommentsProvider>
              <ToastContainer />
            </ToastProvider>
          </UserProvider>
        </ModalProvider>
      </body>
    </html>
  );
}
