import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ToastProvider } from "@/contexts/ToastContext";
import ToastContainer from "@/components/main-components/tissue/ToastContainer/ToastContainer";
import { UserProvider } from "../providers/UserProvider";
import { PostsProvider } from "../providers/PostsProvider";

import { ShowCommentsProvider } from "../providers/ShowCommentsProvider";
import { ModalProvider } from "@/contexts/ModalContext";
import SignInPopUp from "@/components/landing-page/organ/popups/signin-popup/SignInPopUp";
import SignUpPopUp from "@/components/landing-page/organ/popups/signup-popup/SignUpPopUp";
import ConfirmDeletePopUp from "@/components/main-components/organ/popups/confirm-delete-popup/ConfirmDeletePopUp";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ModalProvider>
          <UserProvider>
            <PostsProvider>
              <ToastProvider>
                <ShowCommentsProvider>
                  {children}
                  <SignInPopUp />
                  <SignUpPopUp />
                  <ConfirmDeletePopUp />
                </ShowCommentsProvider>
                <ToastContainer />
              </ToastProvider>
            </PostsProvider>
          </UserProvider>
        </ModalProvider>
      </body>
    </html>
  );
}
